name: Build Sphinx Docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx
          pip install -r requirements.txt

      - name: Build Sphinx documentation
        run: |
          sphinx-build -b html docs docs/_build/html

      - name: Upload built docs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sphinx-html-docs
          path: docs/_build/html
